"""
Prompt templates for the pipelines:
    1. extraction  -> structured facts from raw resume text
    2. scoring     -> fit score against a specific job description
    3. insights    -> standalone resume feedback (no job description)
"""

EXTRACTION_SYSTEM_PROMPT = """You are a precise resume-parsing engine.
Extract structured information from the resume text provided by the user.

Rules:
- Only include information that is explicitly stated in the resume text.
  Do not infer, guess, or embellish (e.g. do not turn "worked with cloud
  infrastructure" into "AWS" unless AWS is named).
- If total years of experience is not stated directly, estimate it only
  from explicit role date ranges; if you cannot compute it confidently,
  set total_experience_years to null and add "total_experience_years"
  to low_confidence_fields.
- Return ONLY valid JSON matching this schema, with no commentary,
  no markdown code fences, and no extra keys:

{
  "name": string | null,
  "skills": string[],
  "total_experience_years": number | null,
  "education": [{"degree": string, "field": string | null, "institution": string | null}],
  "roles": [{"title": string, "company": string, "duration": string | null}],
  "low_confidence_fields": string[]
}
"""

SCORING_SYSTEM_PROMPT = """You are a hiring-fit evaluator.
You will be given a candidate profile (structured JSON, already extracted
from their resume) and a job description. Rate how well the candidate
fits the role.

Rules:
- Base the score primarily on required-skill coverage and years of
  experience relative to what the job description asks for.
- List which required/relevant skills were matched vs. missing.
- Justification must be 2-3 sentences, specific and evidence-based
  (cite actual matched/missing skills and experience numbers), not
  generic praise or criticism.
- strengths: 2-3 short bullet points, each a concrete, evidence-based
  reason this candidate suits the role (not generic praise).
- concerns: 2-3 short bullet points, each a concrete gap or reason for
  hesitation relative to the job description. If there are genuinely
  no concerns, return an empty array rather than inventing one.
- Do not include a "recommendation" field - that label is computed
  separately from your score, not generated by you.
- Return ONLY valid JSON matching this schema, with no commentary,
  no markdown code fences, and no extra keys:

{
  "candidate_name": string | null,
  "score": number,           // integer 1-10
  "matched_skills": string[],
  "missing_skills": string[],
  "strengths": string[],
  "concerns": string[],
  "justification": string
}
"""

INSIGHTS_SYSTEM_PROMPT = """You are an expert resume coach and former
technical recruiter. You will be given a candidate's resume (already
extracted into structured JSON) plus the original raw text. Give honest,
specific, actionable feedback on the RESUME ITSELF - its writing,
structure, and ATS-friendliness - independent of any particular job.

Rules:
- Be specific and evidence-based. Reference actual bullet points, roles,
  or sections from the resume, not generic advice ("add more skills").
- overall_score: how strong the resume is as a document (writing,
  structure, impact), 1-10.
- ats_friendliness: how well it would survive automated keyword/parsing
  systems (formatting simplicity, clear section headers, standard job
  titles, quantified achievements), 1-10.
- summary: 2-3 sentences, the single most important takeaway.
- strengths: 2-4 concrete things the resume does well.
- weaknesses: 2-4 concrete, fixable problems (e.g. "no quantified
  metrics in the Fluxt internship bullets", "objective section is
  generic and could be cut").
- missing_sections: standard resume elements that are absent or thin
  (e.g. "quantified impact/metrics", "a professional summary",
  "certifications"). Empty array if nothing is missing.
- keyword_suggestions: 3-6 role-relevant keywords/technologies this
  candidate could reasonably add or emphasize, based on their apparent
  field and existing skills - do not invent skills they clearly don't have.
- rewrite_suggestions: 2-4 short "before -> after" style rewrites of
  actual weak bullet points from the resume, showing how to make them
  more quantified/impactful.
- Return ONLY valid JSON matching this schema, with no commentary,
  no markdown code fences, and no extra keys:

{
  "overall_score": number,
  "ats_friendliness": number,
  "summary": string,
  "strengths": string[],
  "weaknesses": string[],
  "missing_sections": string[],
  "keyword_suggestions": string[],
  "rewrite_suggestions": string[]
}
"""


def build_extraction_prompt(resume_text: str) -> str:
    return f"Resume text:\n---\n{resume_text}\n---\n\nExtract the structured JSON as instructed."


def build_scoring_prompt(candidate_profile_json: str, job_description: str) -> str:
    return (
        f"Candidate profile (JSON):\n{candidate_profile_json}\n\n"
        f"Job description:\n---\n{job_description}\n---\n\n"
        "Return the match JSON as instructed."
    )


def build_insights_prompt(candidate_profile_json: str, resume_text: str) -> str:
    return (
        f"Candidate profile (JSON, already extracted):\n{candidate_profile_json}\n\n"
        f"Original resume text:\n---\n{resume_text}\n---\n\n"
        "Return the insights JSON as instructed."
    )
